vich_uploader:
    db_driver: orm

    #mappings:
    #    products:
    #        uri_prefix: /images/products
    #        upload_destination: '%kernel.project_dir%/public/images/products'


    mappings:
        upload_images:
            uri_prefix: /images/produits
            upload_destination: '%kernel.project_dir%/public/images/produits'
            namer: vich_uploader.namer_origname # permet d'avoir un nom d'image unique

            inject_on_load: false
            delete_on_update: true
            delete_on_remove: true
