vich_uploader:
    db_driver: orm

    #mappings:
    #    products:
    #        uri_prefix: /images/products
    #        upload_destination: '%kernel.project_dir%/public/images/products'


    mappings:
        upload_images:
            uri_prefix: admin/images/produits
            upload_destination: '%kernel.project_dir%/public/admin/images/produits'
            namer: vich_uploader.namer_origname # permet d'avoir un nom d'image unique

            inject_on_load: false
            delete_on_update: true
            delete_on_remove: true


        upload_fond:
            uri_prefix: admin/images/fond
            upload_destination: '%kernel.project_dir%/public/admin/images/fond'
            namer: vich_uploader.namer_origname # permet d'avoir un nom d'image unique

            inject_on_load: false
            delete_on_update: true
            delete_on_remove: true

        upload_avatar:
            uri_prefix: admin/images/avatar
            upload_destination: '%kernel.project_dir%/public/admin/images/avatar'
            namer: vich_uploader.namer_origname # permet d'avoir un nom d'image unique

            inject_on_load: false
            delete_on_update: true
            delete_on_remove: true